-- MySQL Script generated by MySQL Workbench
-- Wed Apr 28 19:30:56 2021
-- Model: LOBac - Bacterium    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bacterium
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bacterium` ;

-- -----------------------------------------------------
-- Schema bacterium
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bacterium` DEFAULT CHARACTER SET utf8mb4 ;
USE `bacterium` ;

-- -----------------------------------------------------
-- Table `bacterium`.`Taxonomy`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bacterium`.`Taxonomy` ;

CREATE TABLE IF NOT EXISTS `bacterium`.`Taxonomy` (
  `Domain` VARCHAR(75) NOT NULL,
  `Phylum` VARCHAR(75) NOT NULL,
  `Class` VARCHAR(75) NOT NULL,
  `Order` VARCHAR(75) NOT NULL,
  `Family` VARCHAR(75) NOT NULL,
  `Genus` VARCHAR(75) NOT NULL,
  `Species` VARCHAR(75) NOT NULL,
  PRIMARY KEY (`Species`),
  UNIQUE INDEX `Species_UNIQUE` (`Species` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bacterium`.`Bacterium`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bacterium`.`Bacterium` ;

CREATE TABLE IF NOT EXISTS `bacterium`.`Bacterium` (
  `idBacterium` INT NOT NULL,
  `Morphology` ENUM("Coccus", "Bacillus", "Other") NOT NULL,
  `YearOfDiscovery` INT NOT NULL,
  `TypeMetabolism` VARCHAR(45) NOT NULL,
  `Movement` VARCHAR(45) NOT NULL,
  `Morphology_Coccus` VARCHAR(75) NOT NULL,
  `OxygenDemand` ENUM('Aerobic', 'Anaerobic') NOT NULL,
  `GramStain` TINYINT NOT NULL,
  `Taxonomy_Species` VARCHAR(75) NOT NULL,
  UNIQUE INDEX `idBacteria_UNIQUE` (`idBacterium` ASC) VISIBLE,
  UNIQUE INDEX `Morphology_UNIQUE` (`Morphology` ASC) VISIBLE,
  UNIQUE INDEX `YearOfDiscovery_UNIQUE` (`YearOfDiscovery` ASC) VISIBLE,
  UNIQUE INDEX `TypeMetabolism_UNIQUE` (`TypeMetabolism` ASC) VISIBLE,
  UNIQUE INDEX `Movement_UNIQUE` (`Movement` ASC) VISIBLE,
  PRIMARY KEY (`idBacterium`, `Taxonomy_Species`),
  UNIQUE INDEX `Morphology_Coccus_UNIQUE` (`Morphology_Coccus` ASC) VISIBLE,
  UNIQUE INDEX `OxygenDemand_UNIQUE` (`OxygenDemand` ASC) VISIBLE,
  INDEX `fk_Bacterium_Taxonomy1_idx` (`Taxonomy_Species` ASC) VISIBLE,
  CONSTRAINT `fk_Bacterium_Taxonomy1`
    FOREIGN KEY (`Taxonomy_Species`)
    REFERENCES `bacterium`.`Taxonomy` (`Species`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bacterium`.`Genome`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bacterium`.`Genome` ;

CREATE TABLE IF NOT EXISTS `bacterium`.`Genome` (
  `idGenome` INT NOT NULL,
  `Category` ENUM('CIRCULAR', 'LINEAR', 'PLASMID', 'MEGAPLASMID') NULL,
  `Bacterium_idBacterium` INT NOT NULL,
  PRIMARY KEY (`idGenome`),
  UNIQUE INDEX `idGenome_UNIQUE` (`idGenome` ASC) VISIBLE,
  INDEX `fk_Genome_Bacterium1_idx` (`Bacterium_idBacterium` ASC) VISIBLE,
  CONSTRAINT `fk_Genome_Bacterium1`
    FOREIGN KEY (`Bacterium_idBacterium`)
    REFERENCES `bacterium`.`Bacterium` (`idBacterium`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bacterium`.`Disease`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bacterium`.`Disease` ;

CREATE TABLE IF NOT EXISTS `bacterium`.`Disease` (
  `NameDisease` VARCHAR(75) NOT NULL,
  `Symptoms` VARCHAR(45) NULL,
  `HasCure` TINYINT NULL,
  `Description` VARCHAR(500) NULL,
  `Bacterium_idBacterium` INT NOT NULL,
  PRIMARY KEY (`NameDisease`),
  UNIQUE INDEX `NameDisease_UNIQUE` (`NameDisease` ASC) VISIBLE,
  UNIQUE INDEX `Symptoms_UNIQUE` (`Symptoms` ASC) VISIBLE,
  INDEX `fk_Disease_Bacterium1_idx` (`Bacterium_idBacterium` ASC) VISIBLE,
  CONSTRAINT `fk_Disease_Bacterium1`
    FOREIGN KEY (`Bacterium_idBacterium`)
    REFERENCES `bacterium`.`Bacterium` (`idBacterium`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bacterium`.`Gen`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bacterium`.`Gen` ;

CREATE TABLE IF NOT EXISTS `bacterium`.`Gen` (
  `Category` ENUM('CIRCULAR', 'LINEAR', 'PLASMID', 'MEGAPLASMID') NOT NULL,
  `Secuence` TEXT(50000) NOT NULL,
  `Genome_idGenome1` INT NOT NULL,
  PRIMARY KEY (`Category`),
  INDEX `fk_Gen_Genome1_idx` (`Genome_idGenome1` ASC) VISIBLE,
  CONSTRAINT `fk_Gen_Genome1`
    FOREIGN KEY (`Genome_idGenome1`)
    REFERENCES `bacterium`.`Genome` (`idGenome`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
