-- MySQL Script generated by MySQL Workbench
-- Fri Jun 25 21:50:44 2021
-- Model: Bacterium    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bacterium
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bacterium` ;

-- -----------------------------------------------------
-- Schema bacterium
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bacterium` DEFAULT CHARACTER SET utf8mb4 ;
USE `bacterium` ;

-- -----------------------------------------------------
-- Table `bacterium`.`Taxonomy`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bacterium`.`Taxonomy` ;

CREATE TABLE IF NOT EXISTS `bacterium`.`Taxonomy` (
  `Phylum` VARCHAR(150) NOT NULL,
  `Class` VARCHAR(150) NOT NULL,
  `Order` VARCHAR(150) NOT NULL,
  `Family` VARCHAR(150) NOT NULL,
  `Genus` VARCHAR(150) NOT NULL,
  `Species` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`Species`),
  UNIQUE INDEX `Species_UNIQUE` (`Species` ASC) VISIBLE)
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `bacterium`.`Bacterium`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bacterium`.`Bacterium` ;

CREATE TABLE IF NOT EXISTS `bacterium`.`Bacterium` (
  `idBacterium` INT NOT NULL AUTO_INCREMENT,
  `Morphology` ENUM("Coccus", "Bacillus", "Other") NOT NULL,
  `YearOfDiscovery` INT NOT NULL,
  `TypeMetabolism` ENUM("Chemoorganotroph", "Chemolithotroph", "Phototroph") NOT NULL,
  `Movement` VARCHAR(45) NOT NULL,
  `OxygenDemand` ENUM('Aerobic', 'Anaerobic') NOT NULL,
  `GramStain` TINYINT NOT NULL,
  `Taxonomy_Species` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`idBacterium`),
  INDEX `fk_Bacterium_Taxonomy1_idx` (`Taxonomy_Species` ASC) VISIBLE,
  FULLTEXT INDEX `bac_specie` (`Taxonomy_Species`) VISIBLE)
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `bacterium`.`Genome`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bacterium`.`Genome` ;

CREATE TABLE IF NOT EXISTS `bacterium`.`Genome` (
  `idGenome` INT NOT NULL,
  `Category` ENUM('CIRCULAR', 'LINEAR', 'PLASMID', 'MEGAPLASMID') NULL,
  `Bacterium_idBacterium` INT NOT NULL,
  PRIMARY KEY (`idGenome`),
  INDEX `fk_Genome_Bacterium1_idx` (`Bacterium_idBacterium` ASC) VISIBLE)
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `bacterium`.`Disease`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bacterium`.`Disease` ;

CREATE TABLE IF NOT EXISTS `bacterium`.`Disease` (
  `NameDisease` VARCHAR(150) NOT NULL,
  `Symptoms` VARCHAR(500) NULL,
  `HasCure` TINYINT NULL,
  `Description` VARCHAR(500) NULL,
  `Bacterium_idBacterium` INT NOT NULL,
  PRIMARY KEY (`NameDisease`),
  INDEX `fk_Disease_Bacterium1_idx` (`Bacterium_idBacterium` ASC) INVISIBLE)
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `bacterium`.`Gen`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bacterium`.`Gen` ;

CREATE TABLE IF NOT EXISTS `bacterium`.`Gen` (
  `Category` ENUM('CIRCULAR', 'LINEAR', 'PLASMID', 'MEGAPLASMID') NOT NULL,
  `Secuence` TEXT(50000) NOT NULL,
  `Genome_idGenome1` INT NOT NULL,
  PRIMARY KEY (`Category`),
  INDEX `fk_Gen_Genome1_idx` (`Genome_idGenome1` ASC) VISIBLE)
ENGINE = MyISAM;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
