-- MySQL Script generated by MySQL Workbench
-- Wed Apr 28 18:01:08 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Taxonomy`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Taxonomy` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Taxonomy` (
  `Domain` VARCHAR(75) NOT NULL,
  `Phylum` VARCHAR(75) NOT NULL,
  `Class` VARCHAR(75) NOT NULL,
  `Order` VARCHAR(75) NOT NULL,
  `Family` VARCHAR(75) NOT NULL,
  `Genus` VARCHAR(75) NOT NULL,
  `Species` VARCHAR(75) NOT NULL,
  PRIMARY KEY (`Species`),
  UNIQUE INDEX `Species_UNIQUE` (`Species` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Bacterium`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Bacterium` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Bacterium` (
  `idBacterium` INT NOT NULL,
  `Morphology` ENUM("Coccus", "Bacillus", "Other") NOT NULL,
  `YearOfDiscovery` INT NOT NULL,
  `TypeMetabolism` VARCHAR(45) NOT NULL,
  `Movement` VARCHAR(45) NOT NULL,
  `Morphology_Coccus` VARCHAR(75) NOT NULL,
  `OxygenDemand` ENUM('Aerobic', 'Anaerobic') NOT NULL,
  `GramStain` TINYINT NOT NULL,
  UNIQUE INDEX `idBacteria_UNIQUE` (`idBacterium` ASC) VISIBLE,
  UNIQUE INDEX `Morphology_UNIQUE` (`Morphology` ASC) VISIBLE,
  UNIQUE INDEX `YearOfDiscovery_UNIQUE` (`YearOfDiscovery` ASC) VISIBLE,
  UNIQUE INDEX `TypeMetabolism_UNIQUE` (`TypeMetabolism` ASC) VISIBLE,
  UNIQUE INDEX `Movement_UNIQUE` (`Movement` ASC) VISIBLE,
  PRIMARY KEY (`idBacterium`),
  UNIQUE INDEX `Morphology_Coccus_UNIQUE` (`Morphology_Coccus` ASC) VISIBLE,
  UNIQUE INDEX `OxygenDemand_UNIQUE` (`OxygenDemand` ASC) VISIBLE,
  CONSTRAINT `Taxonomy`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Taxonomy` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Genome`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Genome` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Genome` (
  `idGenome` INT NOT NULL,
  `Category` ENUM('CIRCULAR', 'LINEAR', 'PLASMID', 'MEGAPLASMID') NULL,
  `Bacterium_idBacterium` INT NOT NULL,
  PRIMARY KEY (`idGenome`),
  UNIQUE INDEX `idGenome_UNIQUE` (`idGenome` ASC) VISIBLE,
  INDEX `fk_Genome_Bacterium1_idx` (`Bacterium_idBacterium` ASC) VISIBLE,
  CONSTRAINT `fk_Genome_Bacterium1`
    FOREIGN KEY (`Bacterium_idBacterium`)
    REFERENCES `mydb`.`Bacterium` (`idBacterium`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Disease`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Disease` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Disease` (
  `NameDisease` VARCHAR(75) NOT NULL,
  `Symptoms` VARCHAR(45) NULL,
  `HasCure` TINYINT NULL,
  `Description` VARCHAR(500) NULL,
  `Bacterium_idBacterium` INT NOT NULL,
  PRIMARY KEY (`NameDisease`),
  UNIQUE INDEX `NameDisease_UNIQUE` (`NameDisease` ASC) VISIBLE,
  UNIQUE INDEX `Symptoms_UNIQUE` (`Symptoms` ASC) VISIBLE,
  INDEX `fk_Disease_Bacterium1_idx` (`Bacterium_idBacterium` ASC) VISIBLE,
  CONSTRAINT `fk_Disease_Bacterium1`
    FOREIGN KEY (`Bacterium_idBacterium`)
    REFERENCES `mydb`.`Bacterium` (`idBacterium`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Gen`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Gen` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Gen` (
  `Category` ENUM('CIRCULAR', 'LINEAR', 'PLASMID', 'MEGAPLASMID') NOT NULL,
  `Secuence` VARCHAR(50000) NOT NULL,
  `Genome_idGenome` INT NOT NULL,
  PRIMARY KEY (`Category`),
  INDEX `fk_Gen_Genome1_idx` (`Genome_idGenome` ASC) VISIBLE,
  UNIQUE INDEX `Genome_idGenome_UNIQUE` (`Genome_idGenome` ASC) VISIBLE,
  CONSTRAINT `fk_Gen_Genome1`
    FOREIGN KEY (`Genome_idGenome`)
    REFERENCES `mydb`.`Genome` (`idGenome`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
